from src.llm import llm


def evaluate_answer(question, expected_answer, actual_answer):

    prompt = f"""
You are evaluating the quality of an answer generated by a RAG system.

Question:
{question}

Expected Answer:
{expected_answer}

Actual Answer:
{actual_answer}

Evaluate whether the actual answer correctly answers the question
and contains the important information from the expected answer.

Give a score from 0 to 1:

1.0 = Completely correct
0.8 = Mostly correct with minor differences
0.5 = Partially correct
0.2 = Mostly incorrect
0.0 = Completely incorrect

Return ONLY the numeric score.
"""

    response = llm.invoke(prompt)

    try:
        score = float(response.content[0]["text"].strip())
    except ValueError:
        score = 0.0

    return score

def evaluate_faithfulness(question, answer, documents):

    context = "\n\n".join(
        document.page_content
        for document in documents
    )

    prompt = f"""
You are evaluating the faithfulness of an answer generated by a RAG system.

Question:
{question}

Retrieved Context:
{context}

Generated Answer:
{answer}

Determine whether every factual claim in the generated answer
is supported by the retrieved context.

Give a score from 0 to 1:

1.0 = All factual claims are supported by the context
0.8 = Almost all claims are supported, with a minor unsupported detail
0.5 = Some claims are supported and some are unsupported
0.2 = Most claims are unsupported
0.0 = The answer is completely unsupported by the context

Return ONLY the numeric score.
"""

    response = llm.invoke(prompt)

    try:
        score = float(response.content[0]["text"].strip())
    except ValueError:
        score = 0.0

    return score